version: 1.0
download_urls:
  - https://raw.githubusercontent.com/google-research/google-research/master/goemotions/data/train.tsv
  - https://raw.githubusercontent.com/google-research/google-research/master/goemotions/data/dev.tsv
  - https://raw.githubusercontent.com/google-research/google-research/master/goemotions/data/test.tsv
split_filenames:
  train_file: train.tsv
  test_file: test.tsv
  val_file: dev.tsv
download_file_type: tsv
csv_filename: goemotions.csv