os:
  - linux
dist: bionic
language: python
jobs:
  include:
    - python: "3.6"
      env: TENSORFLOW=2.3.1
    - python: "3.7"
      env: TENSORFLOW=2.4.0
    - python: "3.8"
      env: TENSORFLOW=nightly
before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake libsndfile1
install:
  - python -m pip install -U pip
  - |
    if [ $TENSORFLOW == "nightly" ]; then
      cat requirements.txt | sed '/^tensorflow[>=<]/d' > requirements-temp && mv requirements-temp requirements.txt
      cat requirements_horovod.txt | sed 's/\[tensorflow\]//g' > requirements-temp && mv requirements-temp requirements_horovod.txt
      pip install tf-nightly
      HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_MPI=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 pip install --no-cache-dir git+https://github.com/horovod/horovod.git@master
    else
      pip install tensorflow==$TENSORFLOW
    fi
  - HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_MPI=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 pip install --no-cache-dir '.[test]'
script:
  - pip list
  - pytest -v --timeout 300 tests
