output_features:
  - name: loss
    type: number
input_features:
  - column: cat1
    name: cat1
    type: category
  - column: cat2
    name: cat2
    type: category
  - column: cat3
    name: cat3
    type: category
  - column: cat4
    name: cat4
    type: category
  - column: cat5
    name: cat5
    type: category
  - column: cat6
    name: cat6
    type: category
  - column: cat7
    name: cat7
    type: category
  - column: cat8
    name: cat8
    type: category
  - column: cat9
    name: cat9
    type: category
  - column: cat10
    name: cat10
    type: category
  - column: cat11
    name: cat11
    type: category
  - column: cat12
    name: cat12
    type: category
  - column: cat13
    name: cat13
    type: category
  - column: cat14
    name: cat14
    type: category
  - column: cat15
    name: cat15
    type: category
  - column: cat16
    name: cat16
    type: category
  - column: cat17
    name: cat17
    type: category
  - column: cat18
    name: cat18
    type: category
  - column: cat19
    name: cat19
    type: category
  - column: cat20
    name: cat20
    type: category
  - column: cat21
    name: cat21
    type: category
  - column: cat22
    name: cat22
    type: category
  - column: cat23
    name: cat23
    type: category
  - column: cat24
    name: cat24
    type: category
  - column: cat25
    name: cat25
    type: category
  - column: cat26
    name: cat26
    type: category
  - column: cat27
    name: cat27
    type: category
  - column: cat28
    name: cat28
    type: category
  - column: cat29
    name: cat29
    type: category
  - column: cat30
    name: cat30
    type: category
  - column: cat31
    name: cat31
    type: category
  - column: cat32
    name: cat32
    type: category
  - column: cat33
    name: cat33
    type: category
  - column: cat34
    name: cat34
    type: category
  - column: cat35
    name: cat35
    type: category
  - column: cat36
    name: cat36
    type: category
  - column: cat37
    name: cat37
    type: category
  - column: cat38
    name: cat38
    type: category
  - column: cat39
    name: cat39
    type: category
  - column: cat40
    name: cat40
    type: category
  - column: cat41
    name: cat41
    type: category
  - column: cat42
    name: cat42
    type: category
  - column: cat43
    name: cat43
    type: category
  - column: cat44
    name: cat44
    type: category
  - column: cat45
    name: cat45
    type: category
  - column: cat46
    name: cat46
    type: category
  - column: cat47
    name: cat47
    type: category
  - column: cat48
    name: cat48
    type: category
  - column: cat49
    name: cat49
    type: category
  - column: cat50
    name: cat50
    type: category
  - column: cat51
    name: cat51
    type: category
  - column: cat52
    name: cat52
    type: category
  - column: cat53
    name: cat53
    type: category
  - column: cat54
    name: cat54
    type: category
  - column: cat55
    name: cat55
    type: category
  - column: cat56
    name: cat56
    type: category
  - column: cat57
    name: cat57
    type: category
  - column: cat58
    name: cat58
    type: category
  - column: cat59
    name: cat59
    type: category
  - column: cat60
    name: cat60
    type: category
  - column: cat61
    name: cat61
    type: category
  - column: cat62
    name: cat62
    type: category
  - column: cat63
    name: cat63
    type: category
  - column: cat64
    name: cat64
    type: category
  - column: cat65
    name: cat65
    type: category
  - column: cat66
    name: cat66
    type: category
  - column: cat67
    name: cat67
    type: category
  - column: cat68
    name: cat68
    type: category
  - column: cat69
    name: cat69
    type: category
  - column: cat70
    name: cat70
    type: category
  - column: cat71
    name: cat71
    type: category
  - column: cat72
    name: cat72
    type: category
  - column: cat73
    name: cat73
    type: category
  - column: cat74
    name: cat74
    type: category
  - column: cat75
    name: cat75
    type: category
  - column: cat76
    name: cat76
    type: category
  - column: cat77
    name: cat77
    type: category
  - column: cat78
    name: cat78
    type: category
  - column: cat79
    name: cat79
    type: category
  - column: cat80
    name: cat80
    type: category
  - column: cat81
    name: cat81
    type: category
  - column: cat82
    name: cat82
    type: category
  - column: cat83
    name: cat83
    type: category
  - column: cat84
    name: cat84
    type: category
  - column: cat85
    name: cat85
    type: category
  - column: cat86
    name: cat86
    type: category
  - column: cat87
    name: cat87
    type: category
  - column: cat88
    name: cat88
    type: category
  - column: cat89
    name: cat89
    type: category
  - column: cat90
    name: cat90
    type: category
  - column: cat91
    name: cat91
    type: category
  - column: cat92
    name: cat92
    type: category
  - column: cat93
    name: cat93
    type: category
  - column: cat94
    name: cat94
    type: category
  - column: cat95
    name: cat95
    type: category
  - column: cat96
    name: cat96
    type: category
  - column: cat97
    name: cat97
    type: category
  - column: cat98
    name: cat98
    type: category
  - column: cat99
    name: cat99
    type: category
  - column: cat100
    name: cat100
    type: category
  - column: cat101
    name: cat101
    type: category
  - column: cat102
    name: cat102
    type: category
  - column: cat103
    name: cat103
    type: category
  - column: cat104
    name: cat104
    type: category
  - column: cat105
    name: cat105
    type: category
  - column: cat106
    name: cat106
    type: category
  - column: cat107
    name: cat107
    type: category
  - column: cat108
    name: cat108
    type: category
  - column: cat109
    name: cat109
    type: category
  - column: cat110
    name: cat110
    type: category
  - column: cat111
    name: cat111
    type: category
  - column: cat112
    name: cat112
    type: category
  - column: cat113
    name: cat113
    type: category
  - column: cat114
    name: cat114
    type: category
  - column: cat115
    name: cat115
    type: category
  - column: cat116
    name: cat116
    type: category
  - column: cont1
    name: cont1
    type: number
  - column: cont2
    name: cont2
    type: number
  - column: cont3
    name: cont3
    type: number
  - column: cont4
    name: cont4
    type: number
  - column: cont5
    name: cont5
    type: number
  - column: cont6
    name: cont6
    type: number
  - column: cont7
    name: cont7
    type: number
  - column: cont8
    name: cont8
    type: number
  - column: cont9
    name: cont9
    type: number
  - column: cont10
    name: cont10
    type: number
  - column: cont11
    name: cont11
    type: number
  - column: cont12
    name: cont12
    type: number
  - column: cont13
    name: cont13
    type: number
  - column: cont14
    name: cont14
    type: number
combiner:
  type: tabnet
  size: 128
  output_size: 8
  sparsity: 0
  bn_momentum: 0.98
  num_steps: 10
  relaxation_factor: 1
  bn_virtual_bs: 4096
trainer:
  batch_size: 256
  epochs: 300
  early_stop: 30
  learning_rate: 0.01
  optimizer:
    type: adam
  learning_rate_scheduler:
    decay: exponential
    decay_steps: 10000
    decay_rate: 0.9
  validation_metric: root_mean_squared_error
preprocessing:
  split:
    type: fixed
