output_features:
  - name: label
    type: category
input_features:
  - name: review_text
    type: text
    encoder: bert
preprocessing:
  text:
    max_sequence_length: 128
trainer:
  batch_size: 16
  checkpoints_per_epoch: 11
  learning_rate: 0.00002
  #epochs: 5
  evaluate_training_set: False
  learning_rate_scheduler:
    warmup_evaluations: 0
  optimizer:
    type: adamw
  validation_field: label
  validation_metric: accuracy
  epochs: 1
  train_steps: 32000
