output_features:
  - name: label
    type: category
input_features:
  - name: sentence
    type: text
    encoder: bert
    trainable: True
trainer:
  batch_size: 64
  learning_rate: 0.00002
  epochs: 5
  learning_rate_scheduler:
    warmup_evaluations: 0
  optimizer:
    type: adamw
  validation_field: label
  validation_metric: accuracy
preprocessing:
  split:
    type: fixed
