input_features:
  - name: lepton_pT
    type: numerical
  - name: lepton_eta
    type: numerical
  - name: lepton_phi
    type: numerical
  - name: missing_energy_magnitude
    type: numerical
  - name: missing_energy_phi
    type: numerical
  - name: jet_1_pt
    type: numerical
  - name: jet_1_eta
    type: numerical
  - name: jet_1_phi
    type: numerical
  - name: jet_1_b-tag
    type: numerical
  - name: jet_2_pt
    type: numerical
  - name: jet_2_eta
    type: numerical
  - name: jet_2_phi
    type: numerical
  - name: jet_2_b-tag
    type: numerical
  - name: jet_3_pt
    type: numerical
  - name: jet_3_eta
    type: numerical
  - name: jet_3_phi
    type: numerical
  - name: jet_3_b-tag
    type: numerical
  - name: jet_4_pt
    type: numerical
  - name: jet_4_eta
    type: numerical
  - name: jet_4_phi
    type: numerical
  - name: jet_4_b-tag
    type: numerical
  - name: m_jj
    type: numerical
  - name: m_jjj
    type: numerical
  - name: m_lv
    type: numerical
  - name: m_jlv
    type: numerical
  - name: m_bb
    type: numerical
  - name: m_wbb
    type: numerical
  - name: m_wwbb
    type: numerical
output_features:
  - name: label
    type: binary
    weight_regularization: null
combiner:
  type: tabnet
  size: 24  # N_a
  output_size: 26  # N_d
  sparsity: 0.000001  # lambda_sparse
  bn_virtual_divider: 32  # factor to divide batch_size B to get B_v from the paper
  bn_momentum: 0.6  # m_B
  num_steps: 5  # N_steps
  relaxation_factor: 1.5  # gamma
  use_keras_batch_norm: false
  bn_virtual_bs: 512  # B_v
training:
  batch_size: 16384  # B
  eval_batch_size: 500000  # 65536 131072 262144 524288
  epochs: 1000
  early_stop: 20
  learning_rate: 0.02
  optimizer:
    type: adam
  decay: true
  decay_steps: 20000
  decay_rate: 0.9
  staircase: true
  regularization_lambda: 1
  validation_field: label
