version: 1.0
name: mnist
download_urls:
  - http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
  - http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
  - http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
  - http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
sha256:
  t10k-images-idx3-ubyte.gz: 8d422c7b0a1c1c79245a5bcf07fe86e33eeafee792b84584aec276f5a2dbc4e6
  train-images-idx3-ubyte.gz: 440fcabf73cc546fa21475e81ea370265605f56be210a4024d2ca8f203523609
  train-labels-idx1-ubyte.gz: 3552534a0a558bbed6aed32b30c495cca23d567ec52cac8be1a0730e8010255c
  t10k-labels-idx1-ubyte.gz: f7ae60f92e00ec6debd23a6088c31dbd2371eca3ffa0defaefb259924204aec6
preserve_paths:
  - training
  - testing
loader: mnist.MNISTLoader
description: |
  The MNIST database of handwritten digits, available from this page,
  has a training set of 60,000 examples, and a test set of 10,000 examples.
  It is a subset of a larger set available from NIST. The digits have been
  size-normalized and centered in a fixed-size image.
  It is a good database for people who want to try learning techniques and
  pattern recognition methods on real-world data while spending minimal
  efforts on preprocessing and formatting.
  http://yann.lecun.com/exdb/mnist/
output_features:
    - name: label
      type: category
