version: 1.0
name: yelp_reviews
download_urls: https://s3.amazonaws.com/fast-ai-nlp/yelp_review_full_csv.tgz
sha256:
  yelp_review_full_csv.tgz: 56006b0a17a370f1e366504b1f2c3e3754e4a3dda17d3e718a885c552869a559
train_filenames: yelp_review_full_csv/train.csv
test_filenames: yelp_review_full_csv/test.csv
columns:
  - label
  - text
description: |
  The Yelp Reviews dataset
  Details:
      1,569,264 samples from the Yelp Dataset Challenge 2015.
      This subset has 130,000 training samples and 10,000
      testing samples in each star rating.
  Dataset source:
      Character-level Convolutional Networks for Text Classification
      Xiang Zhang et al., 2015
output_features:
  - name: label
    type: category
