version: 1.0
download_urls:
  - "https://s3.amazonaws.com/fast-ai-nlp/amazon_review_polarity_csv.tgz"
split_filenames:
  train_file: train.csv
  test_file: test.csv
download_file_type: csv
csv_filename: amazon_review_polarity.csv