training:
  batch_size: auto #256
  learning_rate: auto #.001
  # validation_metric: accuracy

hyperopt:
  sampler:
    type: ray
    scheduler:
      type: async_hyperband
      time_attr: time_total_s
      max_t: 7200
      grace_period: 72
      # Increased over default to get more pruning/exploration
      reduction_factor: 5
    num_samples: 10

  executor:
    type: ray
    time_budget_s: 7200
