combiner:
  type: concat

training:
  batch_size: auto #256
  learning_rate: auto #.001
  # validation_metric: accuracy

hyperopt:
  # goal: maximize
  parameters:
    combiner.num_fc_layers:
      space: randint
      type: int
      lower: 1
      upper: 4
    combiner.fc_size:
      space: choice
      categories: [128, 256]
    combiner.dropout:
      space: uniform
      type: float
      lower: 0.0
      upper: 0.1
    training.learning_rate:
      space: loguniform
      type: float
      lower: 0.00002
      upper: 0.001
    training.batch_size:
      space: choice
      categories: [64, 128, 256, 512, 1024]

  sampler:
    type: ray
    scheduler:
      type: async_hyperband
      time_attr: time_total_s
    num_samples: 20

  executor:
    type: ray
    time_budget_s: 6000
