version: 1.0
competition: mercedes-benz-greener-manufacturing
archive_filename: mercedes-benz-greener-manufacturing.zip
split_filenames:
  train_file: train.csv.zip
  test_file: test.csv.zip
download_file_type: csv
csv_filename: mercedes-benz-greener-manufacturing.csv
